name: "⚡ Custom RDP Session (4-Core, 16GB RAM)"

on:
  workflow_dispatch:

jobs:
  build:
    name: "🚀 Start Windows RDP Session"
    runs-on: windows-latest # This runner provides 4-cores and 16GB RAM on public repos

    env:
      NGROK_SHAHZIAB: ${{ secrets.NGROK_SHAHZAIB }} # Make sure to set this secret in your repository

    steps:
      - name: "☁️ Cloning Ngrok and starting RDP setup"
        shell: pwsh
        run: |
          # Create a user account
          $password = "your-strong-password-here" # Change this to a secure password
          $user = "runneradmin"
          iex "net user /add $user $password"
          iex "net localgroup administrators $user /add"

          # Enable RDP
          iex "reg add 'HKLM\System\CurrentControlSet\Control\Terminal Server' /v fDenyTSConnections /t REG_DWORD /d 0 /f"
          iex "reg add 'HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' /v UserAuthentication /t REG_DWORD /d 1 /f"

          # Download and set up Ngrok
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip
          ./ngrok.exe authtoken $env:NGROK_SHAHZAIB
          ./ngrok.exe tcp 3389 --log "stdout" > ngrok.log &

          Write-Host "✅ RDP setup complete. Waiting for Ngrok tunnel to establish..."
          Start-Sleep -s 10 # Wait for ngrok to start

      - name: "🔗 Get RDP Connection Details"
        shell: pwsh
        run: |
          $logContent = Get-Content -Path ngrok.log -Wait -Tail 10
          $rdpConnection = ($logContent | Select-String -Pattern "url=(tcp://.+)" | Select-Object -First 1).Matches.Groups[1].Value
          if ($rdpConnection) {
            Write-Host "✅ RDP Connection URL: $rdpConnection"
            Write-Host "   You can connect using the above URL."
            Write-Host "   Username: runneradmin"
            Write-Host "   Password: your-strong-password-here" # The password you set above
          } else {
            Write-Error "❌ Could not find Ngrok URL in the log."
          }

      - name: "⏳ Keep RDP Session Alive"
        shell: pwsh
        run: |
          Write-Host "✅ RDP session is running. This job will continue to run to keep the session alive."
          Write-Host "   To end the session, cancel the GitHub Actions workflow."
          Start-Sleep -s 3600 # Keep alive for 1 hour (max is 6 hours for public repos)
